FROM golang:1.25-alpine AS development

WORKDIR /app

RUN apk add --no-cache git curl postgresql-client && \
    go install github.com/air-verse/air@v1.61.6

COPY go.mod go.sum ./
RUN go mod download

COPY . .

COPY .air.toml ./

ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV PORT=8150

EXPOSE 8150
EXPOSE 2114

CMD ["air", "-c", ".air.toml"]
