FROM golang:1.25-bookworm AS development

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    git ca-certificates tzdata curl postgresql-client \
    && rm -rf /var/lib/apt/lists/* \
    && go install github.com/air-verse/air@v1.61.7

COPY go.mod go.sum ./
RUN go mod download

COPY . .

COPY .air.toml ./

ENV GO111MODULE=on
ENV CGO_ENABLED=0
ENV PORT=8150

EXPOSE 8150
EXPOSE 2114

CMD ["air", "-c", ".air.toml"]
